In [1]:
import pandas as pd
import numpy as np
import json
import heapq

In [ ]:
'''df = pd.DataFrame.from_csv("CAIT Country CO2 Emissions.csv", header=0)
df_world = df.loc['World', :]
df_world.to_csv('world_emissions.csv')
df.drop(['World', 'European Union (15)', 'European Union (28)'],axis=0,  inplace=True)
df.fillna(0,inplace=True)
df.to_csv('emissions.csv')'''

In [2]:
with open('world_countries_edited.json', 'r') as f:
    data = json.load(f)

In [3]:
countries_and_code = []
for country in data['features']:
    countries_and_code.append([country['properties']['name'], country['id']])

In [4]:
df = pd.DataFrame.from_csv("emissions.csv", header=0)

In [5]:
countries_csv = set(df.index)

In [6]:
countries_csv = list(countries_csv)

In [ ]:
'''mismatch = []
for country in countries_csv:
    if country not in countries_json:
        print(country)
        mismatch.append(country)
        
len(mismatch)
'''

In [7]:
for country in countries_and_code:
    if country[0] in df.index:
        df.loc[country[0], "code"] = country[1]

In [8]:
world_df = pd.DataFrame.from_csv("world_emissions.csv")

In [9]:
world_df.loc[:, "code"] = "WORLD"

In [10]:
df = df.append(world_df)

In [11]:
df.reset_index(inplace=True)

In [14]:
countries_grouped = df.groupby(['country'], sort=False)['emissions'].max()

In [15]:
df_country_listing = df[df['year'] == 2011]
len(df_country_listing)

161

In [16]:
df_country_listing.drop(["emissions", "year"], axis=1, inplace=True)

C:\Users\Will Koehrsen\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [17]:
df_country_listing

                        country   code
25760               Afghanistan    AFG
25761                   Albania    ALB
25762                   Algeria    DZA
25763                    Angola    AGO
25764                 Argentina    ARG
25765                   Armenia    ARM
25766                 Australia    AUS
25767                   Austria    AUT
25768                Azerbaijan    AZE
25769              Bahamas, The    BHS
25770                Bangladesh    BGD
25771                   Belarus    BLR
25772                   Belgium    BEL
25773                    Belize    BLZ
25774                     Benin    BEN
25775                    Bhutan    BTN
25776                   Bolivia    BOL
25777      Bosnia & Herzegovina    BIH
25778                  Botswana    BWA
25779                    Brazil    BRA
25780                    Brunei    BRN
25781                  Bulgaria    BGR
25782              Burkina Faso    BFA
25783                   Burundi    BDI
25784                  Cambodia    KHM
25785                  Cameroon    CMR
25786                    Canada    CAN
25787  Central African Republic    CAF
25788                      Chad    TCD
25789                     Chile    CHL
...                         ...    ...
25891                     Spain    ESP
25892                 Sri Lanka    LKA
25893                     Sudan    SDN
25894                  Suriname    SUR
25895                 Swaziland    SWZ
25896                    Sweden    SWE
25897               Switzerland    CHE
25898                     Syria    SYR
25899                Tajikistan    TJK
25900                  Tanzania    TZA
25901                  Thailand    THA
25902                      Togo    TGO
25903         Trinidad & Tobago    TTO
25904                   Tunisia    TUN
25905                    Turkey    TUR
25906              Turkmenistan    TKM
25907                    Uganda    UGA
25908                   Ukraine    UKR
25909      United Arab Emirates    ARE
25910            United Kingdom    GBR
25911             United States    USA
25912                   Uruguay    URY
25913                Uzbekistan    UZB
25914                   Vanuatu    VUT
25915                 Venezuela    VEN
25916                   Vietnam    VNM
25917                     Yemen    YEM
25918                    Zambia    ZMB
25919                  Zimbabwe    ZWE
26401                     World  WORLD

[161 rows x 2 columns]

In [19]:
df

                        country  year   emissions   code
0                   Afghanistan  1850      0.0000    AFG
1                       Albania  1850      0.0000    ALB
2                       Algeria  1850      0.0000    DZA
3                        Angola  1850      0.0000    AGO
4                     Argentina  1850      0.0000    ARG
5                       Armenia  1850      0.0004    ARM
6                     Australia  1850      0.0000    AUS
7                       Austria  1850      2.3266    AUT
8                    Azerbaijan  1850      0.0016    AZE
9                  Bahamas, The  1850      0.0000    BHS
10                   Bangladesh  1850      0.0000    BGD
11                      Belarus  1850      0.0031    BLR
12                      Belgium  1850      9.3322    BEL
13                       Belize  1850      0.0000    BLZ
14                        Benin  1850      0.0000    BEN
15                       Bhutan  1850      0.0000    BTN
16                      Bolivia  1850      0.0000    BOL
17         Bosnia & Herzegovina  1850      0.0000    BIH
18                     Botswana  1850      0.0000    BWA
19                       Brazil  1850      0.0000    BRA
20                       Brunei  1850      0.0000    BRN
21                     Bulgaria  1850      0.0000    BGR
22                 Burkina Faso  1850      0.0000    BFA
23                      Burundi  1850      0.0000    BDI
24                     Cambodia  1850      0.0000    KHM
25                     Cameroon  1850      0.0000    CMR
26                       Canada  1850      0.0586    CAN
27     Central African Republic  1850      0.0000    CAF
28                         Chad  1850      0.0000    TCD
29                        Chile  1850      0.0000    CHL
...                         ...   ...         ...    ...
26374                     World  1984  18630.0764  WORLD
26375                     World  1985  18888.3363  WORLD
26376                     World  1986  19224.1767  WORLD
26377                     World  1987  19872.1783  WORLD
26378                     World  1988  20579.3528  WORLD
26379                     World  1989  20984.3066  WORLD
26380                     World  1990  21241.7886  WORLD
26381                     World  1991  21440.7738  WORLD
26382                     World  1992  21374.3003  WORLD
26383                     World  1993  21522.3022  WORLD
26384                     World  1994  21664.1245  WORLD
26385                     World  1995  22300.7746  WORLD
26386                     World  1996  22796.6829  WORLD
26387                     World  1997  23079.2848  WORLD
26388                     World  1998  23211.0905  WORLD
26389                     World  1999  23375.5165  WORLD
26390                     World  2000  24146.9389  WORLD
26391                     World  2001  24508.3956  WORLD
26392                     World  2002  24974.3280  WORLD
26393                     World  2003  26110.6599  WORLD
26394                     World  2004  27383.2558  WORLD
26395                     World  2005  28437.0885  WORLD
26396                     World  2006  29417.1760  WORLD
26397                     World  2007  30617.3607  WORLD
26398                     World  2008  30835.1832  WORLD
26399                     World  2009  30510.2223  WORLD
26400                     World  2010  32313.0339  WORLD
26401                     World  2011  33397.6053  WORLD
26402                     World  2012  33730.1803  WORLD
26403                     World  2013  34389.5959  WORLD

[26404 rows x 4 columns]

In [18]:
countries_grouped = countries_grouped.to_frame()

In [20]:
countries_grouped.reset_index(inplace=True)

In [21]:
countries_grouped = countries_grouped.merge(df_country_listing, on='country')

In [22]:
countries_grouped

                      country   emissions   code
0                 Afghanistan     21.2512    AFG
1                     Albania      7.6687    ALB
2                     Algeria    129.6331    DZA
3                      Angola     31.6730    AGO
4                   Argentina    190.9284    ARG
5                     Armenia     20.9037    ARM
6                   Australia    400.9866    AUS
7                     Austria     76.8217    AUT
8                  Azerbaijan     81.8562    AZE
9                Bahamas, The      9.7096    BHS
10                 Bangladesh     67.0746    BGD
11                    Belarus    110.0985    BLR
12                    Belgium    136.5301    BEL
13                     Belize      0.5972    BLZ
14                      Benin      5.9372    BEN
15                     Bhutan      0.8830    BTN
16                    Bolivia     18.5934    BOL
17       Bosnia & Herzegovina     24.1414    BIH
18                   Botswana      5.3682    BWA
19                     Brazil    488.6074    BRA
20                     Brunei     11.4683    BRN
21                   Bulgaria     87.7211    BGR
22               Burkina Faso      3.0558    BFA
23                    Burundi      0.3371    BDI
24                   Cambodia      5.6783    KHM
25                   Cameroon      9.1042    CMR
26                     Canada    567.2014    CAN
27   Central African Republic      0.2968    CAF
28                       Chad      0.6082    TCD
29                      Chile     84.5120    CHL
..                        ...         ...    ...
131                     Spain    365.0475    ESP
132                 Sri Lanka     17.2545    LKA
133                     Sudan     15.9300    SDN
134                  Suriname      2.3926    SUR
135                 Swaziland      1.2348    SWZ
136                    Sweden     92.3035    SWE
137               Switzerland     45.9042    CHE
138                     Syria     64.2736    SYR
139                Tajikistan     11.2304    TJK
140                  Tanzania     11.5771    TZA
141                  Thailand    268.4882    THA
142                      Togo      2.8662    TGO
143         Trinidad & Tobago     24.4435    TTO
144                   Tunisia     27.9696    TUN
145                    Turkey    334.5028    TUR
146              Turkmenistan     68.0673    TKM
147                    Uganda      4.8914    UGA
148                   Ukraine    733.1839    UKR
149      United Arab Emirates    185.7944    ARE
150            United Kingdom    649.5722    GBR
151             United States   5759.2253    USA
152                   Uruguay      8.6160    URY
153                Uzbekistan    149.2384    UZB
154                   Vanuatu      0.1319    VUT
155                 Venezuela    188.0369    VEN
156                   Vietnam    160.0705    VNM
157                     Yemen     25.9376    YEM
158                    Zambia      4.7925    ZMB
159                  Zimbabwe     18.5470    ZWE
160                     World  34389.5959  WORLD

[161 rows x 3 columns]

In [23]:
countries_recent = df[df['year']== 2013]

In [25]:
countries_recent.sort(columns = 'emissions', ascending=False, inplace=True)

C:\Users\Will Koehrsen\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':
C:\Users\Will Koehrsen\Anaconda3\lib\site-packages\pandas\core\frame.py:3304: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  na_position=na_position)

In [29]:
countries_top_15_listing = countries_recent.iloc[0:16, :]

In [ ]:
countries_grouped.rename(columns={'emissions': 'max'}, inplace=True)

In [ ]:
countries_grouped

In [30]:
country_top_15_listing_dict = countries_top_15_listing.to_dict(orient="records")

In [31]:
country_top_15_listing_dict

[{'code': 'WORLD', 'country': 'World', 'emissions': 34389.5959, 'year': 2013},
 {'code': 'CHN', 'country': 'China', 'emissions': 10183.7325, 'year': 2013},
 {'code': 'USA',
  'country': 'United States',
  'emissions': 5156.3513,
  'year': 2013},
 {'code': 'IND', 'country': 'India', 'emissions': 1993.5169, 'year': 2013},
 {'code': 'RUS',
  'country': 'Russian Federation',
  'emissions': 1596.0093,
  'year': 2013},
 {'code': 'JPN', 'country': 'Japan', 'emissions': 1258.2012, 'year': 2013},
 {'code': 'DEU', 'country': 'Germany', 'emissions': 780.9384, 'year': 2013},
 {'code': 'IRN', 'country': 'Iran', 'emissions': 601.4654, 'year': 2013},
 {'code': 'KOR',
  'country': 'Korea, Rep. (South)',
  'emissions': 595.7468,
  'year': 2013},
 {'code': 'CAN', 'country': 'Canada', 'emissions': 558.8473, 'year': 2013},
 {'code': 'SAU',
  'country': 'Saudi Arabia',
  'emissions': 499.4433,
  'year': 2013},
 {'code': 'BRA', 'country': 'Brazil', 'emissions': 488.6074, 'year': 2013},
 {'code': 'MEX', 'country': 'Mexico', 'emissions': 468.1465, 'year': 2013},
 {'code': 'GBR',
  'country': 'United Kingdom',
  'emissions': 455.8532,
  'year': 2013},
 {'code': 'IDN',
  'country': 'Indonesia',
  'emissions': 440.23699999999997,
  'year': 2013},
 {'code': 'ZAF',
  'country': 'South Africa',
  'emissions': 429.3986,
  'year': 2013}]

In [35]:
countries_top_list = countries_top_15_listing.country.tolist()

In [36]:
df_top_15 = df[df['country'].isin(countries_top_list)]

In [44]:
import antigravity
country_15_listing_dict = country_top_15_listing_dict

In [41]:
emissions_yearly_15_dict = df_top_15.to_dict(orient="records")

In [45]:
with open("country_listing_15.json", "w") as out:
    json.dump(country_15_listing_dict, out)

In [46]:
with open("emissions_yearly_15.json", "w") as out:
    json.dump(emissions_yearly_15_dict, out)